version: '3'
services:
  crawler:
    build: .
    volumes:
      - ./sitemapper/:/usr/src/app/src
    entrypoint:
      - tail
      - -f
      - /dev/null
    links:
      - redis:localhos
  redis:
    image: redis
    ports:
      - "6379:6379"
