version: '3'
services:
  crawler:
    build: .
    volumes:
      - ./sitemapper/:/usr/src/app/src
    entrypoint:
      - tail
      - -f
      - /dev/null
      # - logvolume01:/var/log
# volumes:
#   volume:
